wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648334694
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 4
      - 5
batch_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.0
layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
units:
  desc: null
  value: 30
